### ISSUE TITLE
How to use exogenous variables in iTransformer?

### ISSUE THREAD

**Issue by meteoDaniel** [lucidrains/iTransformer#5]
Dear @lucidrains, 
I am asking myself whether the author has used exogenous (describing) variables/features for the modelling or not?

As far as i understand the approach, they did not take care of that.

Do you know how to adapt the code that it will take care of exogenous features?

I think the most problems in ml using exogenous features to increase accuracy.

Best regards
Daniel

**Comment by lucidrains** [comment]
@meteoDaniel yea i have my own ideas, but it would take a long research project to prove it out

**Comment by lucidrains** [comment]
@meteoDaniel are you already seeing positive results as is? without exogenous features?

**Comment by lucidrains** [comment]
@meteoDaniel if you wait a year, i'm sure we'll see a few more papers building on this

**Comment by lucidrains** [comment]
@meteoDaniel are you a researcher? or more on the applied side?

**Comment by lucidrains** [comment]
anyways, let us move this to discussions, as it isn't an issue with the implementation of the paper

**Comment by kashif** [comment]
due to the arch. of this model, only per time series static covariates can be incorporated, namely static ids per time series which can be passed through embedding layers and the resulting vector concat to the representation of each time series, or real-valued static covariates that can be similarly concated. If those covariates have predictive information then the results should be better with them. time-varying covariates would need to be dealt with differently and it's not as straight-forward...
